apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend
spec:
  type: NodePort # Cambia a NodePort si necesitas acceso externo
  ports:
    - port: 3001        # El puerto del servicio par que otros se comuniquen conmigo
      protocol: TCP
  selector:
    app: backend        # Selecciona los pods con la etiqueta app: backend
