apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 5173      
    nodePort: 30002
    protocol: TCP
  selector:
    app: frontend
